name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Directory where MkDocs builds the site
