name: Build and Upload Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install xmake
      run: |
        Invoke-WebRequest -Uri https://xmake.io/xmake-v2.6.7-windows-x86_64.zip -OutFile xmake.zip
        Expand-Archive -Path xmake.zip -DestinationPath $env:ProgramFiles
        $env:Path += ";$env:ProgramFiles\xmake"

    - name: Install build dependencies
      run: choco install -y mingw git

    - name: Build the project with xmake
      run: |
        xmake f -c  # Configure the project and clean previous builds
        xmake

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: my_app
        path: build/my_app.exe
